name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag joelhutson/workspaces:dev
    - name: Push the docker image
      run: docker push joelhutson/workspaces:dev
